import app from './js/validator';
import form from './js/form';
import button from './js/buttons-back';
import calendar from './js/calendar';
import feach from './js/feach-price';
import fileLoad from './js/file-load';
import buttonNext2 from './js/button-next2';
import dateTimePicker from './js/date-time__picker';
import singUp from './js/sing-up';
